### ISSUE TITLE
Page reloading and not working

### ISSUE THREAD

**Issue by tpawsDEV** [AndyTargino/wwebjs-electron#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey there. First of all, great initiative!
If you need any help in the future with the project, hit me up.
For me, the types are not working, the tutorial would emit an event of blank page, so i had to start a page in another url and wait it for load and, after that, the page for some reason keeps on reloading and loosing the store.
It starts at the qr code, but even after that, at every action I get a reload and the package stops working.

### Expected behavior

The page shouldn't restart 

### Steps to Reproduce the Bug or Issue

    whatsWindow.window.webContents.once('dom-ready', () => {
      wppClient = new (Client as any)(pieBrowser, whatsWindow);
      wppClient.initialize()
    });

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Ubuntu 22

**Comment by AndyTargino** [comment]
Try starting your project in the main window with **puppeteer-in-electron** and **puppeteer-core**

After that start your whatsapp service separately for window loading:

Remember: Whatsapp loading must be asynchronous to the main loading, however you can make it the main loading according to the needs of your project but obviously it would need changes in the code.

I am open to corrections or implementations in the code, any ideas contact me.

Example in code: 

`

await pie.initialize(global.app);
global.browser = await pie.connect(global.app, puppeteer);

global.mainWindow = new BrowserWindow({
    titleBarStyle: 'hidden',
    minWidth: 1300,
    minHeight: 800,
    title: global.app.name,
    backgroundColor: '#312450',
    show: true,
    webPreferences: {
        preload: path.join(__dirname, "preload", "preload.js"),
        webSecurity: false,
        nodeIntegration: true,
        contextIsolation: false,
        enableRemoteModule: true
    }
});

const whatsapp = new BrowserView({
    width: mainWidth - 30,
    height: mainHeight - 30,
    webPreferences: {
        preload: path.join(__dirname, "..", "preload", "preload.js"),
        nodeIntegration: true,
        headless: true,
        contextIsolation: true,
        enableRemoteModule: true
    },
});
const wbot = new Client(global.browser, whatsapp, { qrTimeoutMs: 0 });
wbot.on('ready', () => {
    console.log('Client is ready!');
});
wbot.on('message', msg => {
    if (msg.body == '!ping') {
        msg.reply('pong');
    }
});
wbot.initialize();

`

**Comment by tpawsDEV** [comment]
I found the issue. 
Actually, the main problem is with how puppeteer-in-electron interprets events.
When I emit a ipc event from the whatsapp client, my pupPage that is linked with the client refreshes.
I am searching for a work around or some fix

**Comment by AndyTargino** [comment]
Any news you can post here that I put in the project as a reference.
