### ISSUE TITLE
Error: Evaluation failed: TypeError: r.findImpl is not a function

### ISSUE THREAD

**Issue by MatteoBelvederesi-NewTechnology** [AndyTargino/wwebjs-electron#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Seems like if a new chat with a new users begin it is gonna trigger this error at message sending:  Error: Evaluation failed: TypeError: r.findImpl is not a function. End of the day some messages got delivered some got this error

### Expected behavior

should work with new chats

### Steps to Reproduce the Bug or Issue

just try to send messages via wwebjs-electron

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

windows electron

**Comment by AndyTargino** [comment]
The library is now updated, try again.
