### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by GabrielKothe** [AndyTargino/wwebjs-electron#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ola, nao estou reportando um bug. Mas estou com duvidas em relacao a instalacao do projeto.
Nao estou conseguindo executar ele no eletron. Estou fazendo um trabalho na facul e gostei muito desse projeto. Queria saber se poderia me dar um suporte na instalacao ou enviar um tutorial em video. Muito obrigado!

### Expected behavior

.

### Steps to Reproduce the Bug or Issue

.

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

.

**Comment by AndyTargino** [comment]
Olá, você deve iniciar a conexão em uma view do electron para ser executada: 

Exemplo


```
const { BrowserView } = require('electron');
const { Client } = require('wwebjs-electron');

const whatsapp_view = new BrowserView({
            width: mainWidth,
            height: mainHeight,
            webPreferences: {
                preload: path.join(__dirname, "preload.js"),
                nodeIntegration: true,
                headless: true, // Isso abre a janela do whatsapp web caso sejA necessário, padrão é FALSE
                contextIsolation: true,
                enableRemoteModule: true
    },
});

const wbot = new Client(global.browser, whatsapp_view, { qrTimeoutMs: 0 });
  
  
wbot.on('ready', () => {
            console.log('Client is ready!');
        });

        wbot.on("qr", (qr) => {
            qrcode.generate(qr, { small: true });
        });

        wbot.on("authenticated", (session) => {
            console.error('autenticado');
        });

        wbot.on("auth_failure", msg => {
            console.error('erro ao autenticar', msg);
        })

        // Receber e enviar mensagens pela view com o wwebjs-electron
        wbot.on('message', msg => {
            console.log('evento de mensagem')
        });

 wbot.initialize();
```
